# This is a basic workflow to help you get started with Actions

name: armtemplatedeploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.878809ce-deff-45f1-8299-d5df1b418a9e }}","clientSecret":"${{ secrets.KDD8Q~l_l_lHE8hqJSyPA6Y.jo22XRHFWXhtQbkL }}","subscriptionId":"${{ secrets.8bf5716e-cbb9-4bef-86f6-42ed7d1a872a }}","tenantId":"${{ secrets.ac1df4ad-5702-41e4-8882-db5c910ca664 }}"}'
