# This is a basic workflow to help you get started with Actions

name: armtemplatedeploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: Azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          client-id: ${{ secrets.SP_CLIENT_ID }}

          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          # creds: ${{ secrets.AZURE.CREDENTIALS}}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 8bf5716e-cbb9-4bef-86f6-42ed7d1a872a
          region: Westeurope
          template: ./arm-templates/resourcegroup.json
          parameters: location="Westeurope"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 8bf5716e-cbb9-4bef-86f6-42ed7d1a872a
          template: ./arm-templates/storageaccount.json
          parameters: sku=Standard_LRS
            storageAccountName=robbin003
            location="Westeurope"
          deploymentMode: incremental

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 8bf5716e-cbb9-4bef-86f6-42ed7d1a872a
          template: ./arm-templates/virtualmachine.json
          parameters: adminPassword="My$ecureP@aaword!"
          deploymentMode: incremental
